spring:
  profiles:
    default: local
  config:
    import: optional:file:.env[.properties]

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration-ms: 3600000   # 1 hour
    refresh-expiration-sec: 2592000   # 30 days
  time:
    zone: America/Los_Angeles
  db:
    logs:
      days-to-keep: 7
