spring:
  profiles:
    default: local
  config:
    import: optional:file:skilltracker-app/.env[.properties]
  cache:
    caffeine:
      spec: maximumSize=5000,expireAfterWrite=10m,expireAfterAccess=30m

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration-ms: 3600000   # 1 hour
    refresh-expiration-sec: 2592000   # 30 days
  time:
    zone: America/Los_Angeles
  db:
    logs:
      days-to-keep: 7
